; Ripped from a Giana Sisters crack intro
; Great Giana Sisters, The (1987)(Rainbow Arts)[cr REM][t +9 REM][a].d64

!byte COLOR_BROWN, COLOR_DARK_GREY, COLOR_BROWN, COLOR_DARK_GREY
!byte COLOR_RED
!byte COLOR_ORANGE
!byte COLOR_PINK
!byte COLOR_LIGHT_GREY
!byte COLOR_LIGHT_GREEN
!byte COLOR_YELLOW
!byte COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE 
!byte COLOR_YELLOW
!byte COLOR_LIGHT_GREEN
!byte COLOR_LIGHT_GREY
!byte COLOR_PINK
!byte COLOR_ORANGE
!byte COLOR_RED
