LUMA_NEW_0_COLOR_BLACK         = $00

LUMA_NEW_1_COLOR_BROWN         = $09
LUMA_NEW_1_COLOR_BLUE          = $06

LUMA_NEW_2_COLOR_DARK_GREY     = $0B
LUMA_NEW_2_COLOR_RED           = $02

LUMA_NEW_3_COLOR_PURPLE        = $04
LUMA_NEW_3_COLOR_ORANGE        = $08

LUMA_NEW_4_COLOR_GREY          = $0C
LUMA_NEW_4_COLOR_LIGHT_BLUE    = $0E

LUMA_NEW_5_COLOR_GREEN         = $05
LUMA_NEW_5_COLOR_PINK          = $0A

LUMA_NEW_6_COLOR_CYAN          = $03
LUMA_NEW_6_COLOR_LIGHT_GREY    = $0F

LUMA_NEW_7_COLOR_YELLOW        = $07
LUMA_NEW_7_COLOR_LIGHT_GREEN   = $0D

LUMA_NEW_8_COLOR_WHITE         = $01
