LUMA_OLD_0_COLOR_BLACK         = $00

LUMA_OLD_1_COLOR_RED           = $02
LUMA_OLD_1_COLOR_BROWN         = $09
LUMA_OLD_1_COLOR_DARK_GREY     = $0B
LUMA_OLD_1_COLOR_BLUE          = $06

LUMA_OLD_2_COLOR_GREY          = $0C
LUMA_OLD_2_COLOR_PURPLE        = $04
LUMA_OLD_2_COLOR_GREEN         = $05
LUMA_OLD_2_COLOR_LIGHT_BLUE    = $0E
LUMA_OLD_2_COLOR_ORANGE        = $08
LUMA_OLD_2_COLOR_PINK          = $0A

LUMA_OLD_3_COLOR_CYAN          = $03
LUMA_OLD_3_COLOR_YELLOW        = $07
LUMA_OLD_3_COLOR_LIGHT_GREEN   = $0D
LUMA_OLD_3_COLOR_LIGHT_GREY    = $0F

LUMA_OLD_4_COLOR_WHITE         = $01

